# Use the latest version of PHP as the base image
FROM php:latest

# Set the working directory to /app
WORKDIR /app

# Install any required extensions and packages
RUN docker-php-ext-install pdo_mysql

# Copy the contents of the current directory into the container at /app
COPY . /app

# Expose port 8000
EXPOSE 8000

# Start the PHP development server when the container starts
CMD ["php", "artisan", "serve", "--host=0.0.0.0", "--port=80"]
